# SPDX-FileCopyrightText: : 2017-2023 The PyPSA-Eur Authors
#
# SPDX-License-Identifier: CC0-1.0

# docs in https://pypsa-eur.readthedocs.io/en/latest/configuration.html#run
run:
  prefix: 20250414-NEP-gas
  
# docs in https://pypsa-eur.readthedocs.io/en/latest/configuration.html#sector
sector:
  bev_dsm_availability: 0
  heat_pump_flexibility: false
  
solving:
  test: 8