# SPDX-FileCopyrightText: : 2017-2023 The PyPSA-Eur Authors
#
# SPDX-License-Identifier: CC0-1.0

# docs in https://pypsa-eur.readthedocs.io/en/latest/configuration.html#run
run:
  prefix: 20250414-NEP-flex
  
# docs in https://pypsa-eur.readthedocs.io/en/latest/configuration.html#sector
sector:
  bev_dsm_availability: 0.5
  heat_pump_flexibility: true 

  low_voltage_dsm:
    enable: true
    #scenario: "enhanced_flexibility"  # Add this identifier
    "2030":
      electricity:
        s_util: 0.67
        s_flex: 0.5
        s_inc: 1
        s_dec: 0
        delta_t: 1
      industry electricity:
        s_util: 0.67
        s_flex: 0.5
        s_inc: 0.9
        s_dec: 0.5
        delta_t: 2
    "2040":
      electricity:
        s_util: 0.67
        s_flex: 0.5
        s_inc: 1
        s_dec: 0
        delta_t: 1
      industry electricity:
        s_util: 0.67
        s_flex: 0.5
        s_inc: 0.9
        s_dec: 0.5
        delta_t: 2
    "2045":
      electricity:
        s_util: 0.67
        s_flex: 0.5
        s_inc: 1
        s_dec: 0
        delta_t: 1
      industry electricity:
        s_util: 0.67
        s_flex: 0.5
        s_inc: 0.9
        s_dec: 0.5
        delta_t: 3

solving:
  options:
    load_shedding: 1200
  constraints:
    test: 4
    limits_capacity_max:
      Generator:
        load:
          DE:
            2030: 1.594
            2037: 2.063
            2040: 2.631
            2045: 3
      Link:
        DSM dispatch:
          DE:
            2030: 3
            2037: 6
            2040: 9
            2045: 12
        DSM charge:
          DE:
            2030: 3
            2037: 6
            2040: 9
            2045: 12
        # H2 OCGT:
        #   DE:
        #     2030: 94.1
        #     2035: 94.1
        #     2040: 94.1
        #     2045: 94.1
        H2 Fuel Cell:
          DE:
            2025: 0
            2035: 0
            2040: 0
            2045: 0
        battery discharger:
          DE:
            2030: 15
            2035: 33.2
            2040: 71.1
            2045: 109
        home battery discharger:
          DE:
            2030: 54.3
            2035: 111.8
            2040: 169.3
            2045: 226.8 
    limits_capacity_min:
      Link:
        DSM dispatch:
          DE:
            2030: 3
            2037: 6
            2040: 9
            2045: 12
        DSM charge:
          DE:
            2030: 3
            2035: 6
            2040: 9
            2045: 12
        battery discharger:
          DE:
            2030: 10
            2035: 16
            2040: 35.6
            2045: 54.5
        home battery discharger:
          DE:
            2030: 27.1
            2035: 55.9
            2040: 84.6
            2045: 113.4  
    limits_volume_min:
      water central tank:
        DE:
          2020: 0
          2025: 0
          2030: 1000
          2035: 1500
          2040: 3000
          2045: 3500
      # water decentral tank:
      #   DE:
      #     2020: 0
      #     2025: 0
      #     2030: 50
      #     2035: 100
      #     2040: 200
      #     2045: 300
      battery: 
        DE:
          2030: 10
          2035: 50
          2040: 111
          2045: 216
      home battery:
        DE:
          2030: 65.1
          2035: 138.1
          2040: 211.2
          2045: 284.2
    limits_volume_max:
      battery: 
        DE:
          2030: 20
          2035: 70
          2040: 223.0
          2045: 433.5
      home battery:
        DE:
          2030: 130.2
          2035: 276.3
          2040: 422.4
          2045: 568.5